sudo: required
language: python
services:
  - docker
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python uber4movers/flask-sqlalchemy/test.py
after_success:
  - docker --version  # document the version travis is using
  - docker build -t python-barcode .
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push amitre/python-barcode;
    fi
